name: coverage

name: codacy-coverage-reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: f477224546f843cc8e65872efb35d30a
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: ./coverage/clover.xml
